export const categories: { [key: string]: string[] } = {
  electronics: [
    "Smartphone",
    "Laptop",
    "Tablet",
    "Power Bank",
    "Solar Panel",
    "Television",
    "Inverter",
    "Speakers",
  ],
  clothes: [
    "Shirt",
    "Pants",
    "Jacket",
    "Shoes",
    "Dresses",
    "Underwear",
    "Sportswear",
    "Caps",
  ],
  foods: [
    "Instant Noodles",
    "Snacks",
    "Biscuits",
    "Soft Drinks",
    "Cooking Oil",
    "Rice",
    "Sugar",
    "Canned Fish",
  ],
  machinery: [
    "Brick Maker",
    "Generator",
    "Water Pump",
    "Motorcycle Engine",
    "Agricultural Machine",
    "Rice Milling Machine",
    "Welding Machine",
  ],
  construction: [
    "Tiles",
    "Steel Rods",
    "Roof Sheets",
    "Paint",
    "PVC Pipes",
    "Electrical Cables",
  ],
  household: [
    "Cookware",
    "Plastic Chairs",
    "Mattress",
    "Bed Sheets",
    "Mosquito Nets",
    "Gas Cookers",
    "Fans",
  ],
  beauty: [
    "Wigs",
    "Hair Extensions",
    "Makeup Kits",
    "Skin Creams",
    "Perfumes",
    "Lotions",
    "Bar Soaps",
  ],
  accessories: [
    "Watches",
    "Handbags",
    "Jewelry",
    "Belts",
    "Sunglasses",
    "Wallets",
  ],
  transport: [
    "Motorcycles",
    "Scooters",
    "Bicycles",
    "Tricycles",
    "Auto Spare Parts",
    "Tires",
    "Car Batteries",
  ],
  baby_products: [
    "Baby Diapers",
    "Baby Clothes",
    "Baby Toys",
    "Strollers",
    "Feeding Bottles",
    "Baby Powder",
  ],
  furniture: [
    "Plastic Tables",
    "Office Chairs",
    "Sofas",
    "Beds",
    "Wardrobes",
    "School Desks",
  ],
  health: [
    "Face Masks",
    "Gloves",
    "Herbal Medicines",
    "Blood Pressure Monitors",
    "Wheelchairs",
    "Sanitizers",
  ],
  telecom: [
    "Mobile Accessories",
    "Chargers",
    "Earphones",
    "Routers",
    "Walkie Talkies",
  ],
  stationery: [
    "Notebooks",
    "Pens",
    "Pencils",
    "School Bags",
    "Chalk",
    "Whiteboards",
    "Printers",
  ],
  sports: [
    "Football Jerseys",
    "Sports Shoes",
    "Football",
    "Bicycles",
    "Dumbbells",
    "Skipping Ropes",
  ],
  travel: [
    "Luggage Bags",
    "Travel Backpacks", 
    "Travel Pillows",
    "Passport Holders",
    "Travel Adapters",
  ],
  education: [
    "Textbooks",
    "E-learning Devices", 
    "Scientific Calculators",
    "Educational Software",
    "Online Course Subscriptions",
  ],
};
